name: master_helper
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  image_picker: ^1.1.2
  another_flushbar: ^1.10.29
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  window_manager: ^0.4.2
  shared_preferences: ^2.3.2
  flutter_slidable: ^3.1.1
  toastification: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.1.0
  build_runner: ^2.4.12
  freezed: null

flutter:
  uses-material-design: true
# flutter_intl:
#   enabled: true
