name: slasher
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  flutter_bloc:
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.1.0
  build_runner: ^2.4.12
  freezed:

flutter:
  uses-material-design: true
